/* Satstreet Resource Centre — Research the Hub */
const NOTION='https://api.notion.com/v1';const NOTION_VERSION='2022-06-28';
const HUB=cleanId(process.env.NOTION_KNOWLEDGE_HUB_PAGE?.trim()||'3bbe562f-a5bd-80f2-93c6-ddfe1462cd20');
function cleanId(v:string){const r=v.replace(/-/g,'');return /^[0-9a-f]{32}$/i.test(r)?`${r.slice(0,8)}-${r.slice(8,12)}-${r.slice(12,16)}-${r.slice(16,20)}-${r.slice(20)}`:v}
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':'no-store'}})}
async function notion(path:string,init:RequestInit={}){const token=process.env.NOTION_TOKEN?.trim();if(!token)throw new Error('NOTION_TOKEN is not set in the Netlify environment');const r=await fetch(NOTION+path,{...init,headers:{authorization:`Bearer ${token}`,'Notion-Version':NOTION_VERSION,'content-type':'application/json',...(init.headers||{})},signal:AbortSignal.timeout(10000)});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out?.message||`Notion ${r.status}`);return out}
const plain=(a:any[]|undefined)=>(a||[]).map(x=>x?.plain_text??x?.text?.content??'').join('').trim();
function pageTitle(p:any){for(const v of Object.values(p?.properties||{})){if((v as any)?.type==='title')return plain((v as any).title)}return'Untitled'}
async function children(id:string){const out:any[]=[];let cursor='';do{const qs=new URLSearchParams({page_size:'100'});if(cursor)qs.set('start_cursor',cursor);const r=await notion(`/blocks/${cleanId(id)}/children?${qs}`);out.push(...(r.results||[]));cursor=r.has_more?String(r.next_cursor||''):''}while(cursor);return out}
function blockText(b:any){const p=b?.[b.type]||{};if(Array.isArray(p.rich_text))return plain(p.rich_text);if(b.type==='child_page')return String(p.title||'');if(b.type==='table_row')return(p.cells||[]).map((c:any[])=>plain(c)).join(' | ');return''}
async function collectPage(pageId:string,depth:number,seen:Set<string>,pages:any[],limit:{n:number}){if(limit.n<=0||depth>4||seen.has(pageId))return;seen.add(pageId);limit.n--;const page=await notion(`/pages/${cleanId(pageId)}`);const blocks=await children(pageId);const parts:string[]=[];const childPages:string[]=[];for(const b of blocks){const t=blockText(b);if(t)parts.push(t);if(b.type==='child_page')childPages.push(cleanId(b.id));if(b.has_children&&b.type!=='child_page'){try{for(const n of await children(b.id)){const nt=blockText(n);if(nt)parts.push(nt);if(n.type==='child_page')childPages.push(cleanId(n.id))}}catch{}}}const text=parts.join('\n').replace(/\n{3,}/g,'\n\n').trim();if(text)pages.push({pageId:cleanId(pageId),title:pageTitle(page),url:page.url||'',text:text.slice(0,24000),edited:page.last_edited_time||null});for(const c of childPages){if(limit.n<=0)break;await collectPage(c,depth+1,seen,pages,limit)}}
function terms(q:string){const stop=new Set(['what','which','when','where','why','how','does','from','with','that','this','into','about','have','their','there','would','could','should','the','and','for','are','was','were','you','your','our','its']);return Array.from(new Set((q.toLowerCase().match(/[a-z0-9]{3,}/g)||[]).filter(x=>!stop.has(x))))}
function rank(query:string,pages:any[]){const ts=terms(query),out:any[]=[];for(const p of pages){const paras=p.text.split(/\n+/).map((x:string)=>x.trim()).filter(Boolean);for(let i=0;i<paras.length;i++){const chunk=paras.slice(i,i+3).join(' ').slice(0,1800),low=chunk.toLowerCase();let score=0;for(const t of ts){score+=(low.split(t).length-1)*2;if(p.title.toLowerCase().includes(t))score+=4}if(query.length>5&&low.includes(query.toLowerCase()))score+=12;if(score>0)out.push({title:p.title,url:p.url,pageId:p.pageId,edited:p.edited,excerpt:chunk,score})}}out.sort((a,b)=>b.score-a.score);const sel:any[]=[],per=new Map<string,number>();for(const x of out){const n=per.get(x.pageId)||0;if(n>=3)continue;sel.push(x);per.set(x.pageId,n+1);if(sel.length>=10)break}return sel}
async function synthesize(question:string,passages:any[]){const key=process.env.ANTHROPIC_API_KEY?.trim(),model=process.env.ANTHROPIC_MODEL?.trim();if(!key||!model)return null;const context=passages.map((p,i)=>`[${i+1}] ${p.title}\n${p.excerpt}\nSource: ${p.url}`).join('\n\n');const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':key,'anthropic-version':'2023-06-01','content-type':'application/json'},body:JSON.stringify({model,max_tokens:850,temperature:.2,system:'You are the Satstreet Knowledge Hub research assistant. Answer only from the supplied Satstreet Knowledge Hub excerpts. Be clear, concise and educational. If source material is insufficient, say so. Do not give investment, legal, tax or custody advice. Cite supporting excerpts inline using [1], [2], etc. Never invent a citation.',messages:[{role:'user',content:`Question: ${question}\n\nKnowledge Hub excerpts:\n${context}`}] }),signal:AbortSignal.timeout(20000)});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out?.error?.message||`Anthropic ${r.status}`);return(out?.content||[]).filter((x:any)=>x.type==='text').map((x:any)=>x.text).join('\n').trim()}
export default async function handler(request:Request){if(request.method!=='POST')return json({error:'Use POST.'},405);try{const body=await request.json().catch(()=>({})) as any;const question=String(body?.question||'').trim().slice(0,500);if(question.length<3)return json({error:'Ask a complete question.'},400);const pages:any[]=[];await collectPage(HUB,0,new Set<string>(),pages,{n:55});const passages=rank(question,pages);if(!passages.length)return json({answer:null,mode:'retrieval',passages:[],message:'No relevant Knowledge Hub material was found.'});const answer=await synthesize(question,passages);return json({answer,mode:answer?'ai':'retrieval',passages:passages.slice(0,6).map((p,i)=>({...p,citation:i+1})),message:answer?null:'Relevant live Knowledge Hub material is shown below. To enable synthesized answers, set ANTHROPIC_API_KEY and ANTHROPIC_MODEL in Netlify.',source:'Notion Knowledge Hub'})}catch(e){return json({error:e instanceof Error?e.message:'Research request failed.'},500)}}
export const config={path:'/api/resource-research'};
