/* Satstreet Resource Centre — lazy Notion reader. */
const NOTION='https://api.notion.com/v1';
const NOTION_VERSION='2022-06-28';
const ROOT=cleanId(process.env.NOTION_RESOURCES_PAGE?.trim()||'3c0e562f-a5bd-81d8-b8c5-cc4d048593fc');
const HUB=cleanId(process.env.NOTION_KNOWLEDGE_HUB_PAGE?.trim()||'3bbe562f-a5bd-80f2-93c6-ddfe1462cd20');
const CACHE='public, max-age=120, stale-while-revalidate=600';
function cleanId(v:string){const r=v.replace(/-/g,'');return /^[0-9a-f]{32}$/i.test(r)?`${r.slice(0,8)}-${r.slice(8,12)}-${r.slice(12,16)}-${r.slice(16,20)}-${r.slice(20)}`:v}
function json(data:unknown,status=200,cache=CACHE){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':cache}})}
async function notion(path:string,init:RequestInit={}){const token=process.env.NOTION_TOKEN?.trim();if(!token)throw new Error('NOTION_TOKEN is not set in the Netlify environment');const r=await fetch(NOTION+path,{...init,headers:{authorization:`Bearer ${token}`,'Notion-Version':NOTION_VERSION,'content-type':'application/json',...(init.headers||{})},signal:AbortSignal.timeout(8000)});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.message||`Notion ${r.status}`);return body}
const plain=(a:any[]|undefined)=>(a||[]).map(x=>x?.plain_text??x?.text?.content??'').join('').trim();
const rich=(a:any[]|undefined)=>(a||[]).map(x=>({text:String(x?.plain_text??x?.text?.content??''),href:x?.href||x?.text?.link?.url||null,bold:!!x?.annotations?.bold,italic:!!x?.annotations?.italic,underline:!!x?.annotations?.underline,strikethrough:!!x?.annotations?.strikethrough,code:!!x?.annotations?.code})).filter(x=>x.text);
function pageTitle(p:any){for(const v of Object.values(p?.properties||{})){if((v as any)?.type==='title')return plain((v as any).title)}return''}
function iconOf(i:any){if(!i)return null;if(i.type==='emoji')return i.emoji||null;if(i.type==='external')return i.external?.url||null;if(i.type==='file')return i.file?.url||null;return null}
function pageSummary(p:any){return{id:cleanId(p.id),title:pageTitle(p)||'Untitled',edited:p.last_edited_time||null,icon:iconOf(p.icon)}}
async function fetchPage(id:string){return notion(`/pages/${cleanId(id)}`)}
async function blockChildren(id:string){const out:any[]=[];let cursor='';do{const qs=new URLSearchParams({page_size:'100'});if(cursor)qs.set('start_cursor',cursor);const r=await notion(`/blocks/${cleanId(id)}/children?${qs}`);out.push(...(r.results||[]));cursor=r.has_more?String(r.next_cursor||''):''}while(cursor);return out}
const structural=new Set(['column','column_list','table','synced_block','toggle','callout']);
async function normalizeBlock(b:any,depth:number):Promise<any>{const type=b.type,p=b[type]||{},base:any={id:cleanId(b.id),type};if(['paragraph','heading_1','heading_2','heading_3','quote','bulleted_list_item','numbered_list_item','toggle','to_do'].includes(type)){base.rich=rich(p.rich_text);base.text=plain(p.rich_text);if(type==='to_do')base.checked=!!p.checked}else if(type==='callout'){base.rich=rich(p.rich_text);base.text=plain(p.rich_text);base.icon=iconOf(p.icon);base.color=p.color||''}else if(type==='code'){base.rich=rich(p.rich_text);base.text=plain(p.rich_text);base.language=p.language||''}else if(type==='child_page'){base.pageId=cleanId(b.id);base.title=p.title||'Untitled'}else if(type==='bookmark'||type==='embed'){base.url=p.url||'';base.text=p.caption?plain(p.caption):''}else if(['image','video','file','pdf'].includes(type)){base.url=p.type==='external'?p.external?.url||'':p.file?.url||'';base.text=plain(p.caption)}else if(type==='link_preview'){base.url=p.url||''}else if(type==='link_to_page'&&p.type==='page_id'){base.pageId=cleanId(p.page_id);base.title='Linked page'}else if(type==='table_row'){base.cells=(p.cells||[]).map((c:any[])=>rich(c))}else if(!b.has_children&&type!=='divider'){return null}
  // Recurse only through layout/container blocks. Child pages remain lazy and
  // are fetched only when the visitor opens them.
  if(b.has_children&&type!=='child_page'&&depth<4&&(structural.has(type)||!['paragraph','heading_1','heading_2','heading_3','quote','bulleted_list_item','numbered_list_item','code','image','video','file','pdf','bookmark','embed','link_preview'].includes(type))){const kids=await blockChildren(b.id);base.children=(await Promise.all(kids.map((x:any)=>normalizeBlock(x,depth+1)))).filter(Boolean)}
  return base}
async function readPage(id:string){const page=await fetchPage(id);const kids=await blockChildren(id);return{page:pageSummary(page),blocks:(await Promise.all(kids.map((x:any)=>normalizeBlock(x,0)))).filter(Boolean)}}
async function searchPages(query:string){const res=await notion('/search',{method:'POST',body:JSON.stringify({query,filter:{property:'object',value:'page'},sort:{direction:'descending',timestamp:'last_edited_time'},page_size:20})});return(res.results||[]).slice(0,10).map(pageSummary)}
export default async function handler(request:Request){const url=new URL(request.url),requestedPage=url.searchParams.get('page')?.trim(),q=url.searchParams.get('search')?.trim();try{if(q){if(q.length<2)return json({results:[],query:q});return json({results:await searchPages(q.slice(0,100)),query:q,root:ROOT,hub:HUB})}const id=cleanId(requestedPage||ROOT);if(!/^[0-9a-f-]{36}$/i.test(id))return json({error:'Invalid resource page.'},400,'no-store');/* The Notion integration itself is the permission boundary: it is shared only with the Resources tree. Avoid ancestor-walking here because that added several API calls to every click. */return json({...await readPage(id),root:ROOT,hub:HUB,source:'Notion'})}catch(e){const m=e instanceof Error?e.message:'Unable to load Notion resources.';return json({error:m,hint:m.includes('NOTION_TOKEN')?'Set NOTION_TOKEN in Netlify.':'Make sure the requested Resources page is shared with the Satstreet Notion integration.'},500,'no-store')}}
export const config={path:'/api/resources'};